language: go
arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
install: skip
script:
  - docker build -t toyangdon/oracle_jdk:1.8 .
  - docker push toyangdon/oracle_jdk:1.8
